# -*- coding: utf-8 -*-
"""Homework.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13sJsKKckGO5WwbWdnH_Cj9sveiunBUPx
"""

class SifreCözme:
  def __init__(self, kayma):
    self.kayma = kayma
    self.alfabe = "abcdefghijklmnopqrstuvwxyz"

  def sifrele (self, metin):
    sifreli_metin = ""
    for harf in metin:
      if harf.lower() in self.alfabe:
        k_index = (self.alfabe.index(harf.lower()) + self.kayma) % len(self.alfabe)
        yeni_harf = self.alfabe[k_index]
        sifreli_metin += yeni_harf
      else:
        sifreli_metin += harf
    return sifreli_metin


  def coz (self, metin):
    cozulmus_metin = ""
    for harf in metin:
      if harf.lower() in self.alfabe:
        k_index = (self.alfabe.index(harf.lower()) - self.kayma) % len(self.alfabe)
        yeni_harf = self.alfabe[k_index]
        cozulmus_metin += yeni_harf
      else:
        cozulmus_metin += harf
    return cozulmus_metin


sifreleyici= SifreCözme(5)

sifreli_metin = "ymj vznhp gwtbs ktc ozrux tajw ymj qfed itl"
cozulmus_metin = sifreleyici.coz(sifreli_metin)
print(f"çözülmüş metin: {cozulmus_metin}")

metin = input("Lütfen şifrelemek istediğiniz metni girin: ")
sifreli = sifreleyici.sifrele(metin)
print("Şifrelenmiş metin:", sifreli)

metin = input("Lütfen çözmek istediğiniz metni girin: ")
cozulmus = sifreleyici.coz(sifreli)
print("Çözülen metin:", cozulmus)

