# -*- coding: utf-8 -*-
"""Şifre Kırıcı

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lU1w3RzQbb03ruzAV5actQ94tP52MVEF
"""

# Python kullanarak tersine mühendislik yaparak algoritmayı ters çevir.

def decrypt_message(encrypted_message):
    decrypted_message = ""

    for char in encrypted_message:
        if char.isalpha():
            if char.islower():
                new_char = chr((ord(char) - ord('a') - 5) % 26 + ord('a'))
            else:
                new_char = chr((ord(char) - ord('A') - 5) % 26 + ord('A'))
            decrypted_message += new_char
        else:
            decrypted_message += char

    return decrypted_message

# Şifreli mesaj
encrypted_message = "ymj vznhp gwtbs ktc ozrux tajw ymj qfed itl"
original_message = decrypt_message(encrypted_message)
print("Orijinal mesaj:", original_message)

# Bonus: Kullanıcının kendi mesajını şifreleyip geri açabileceği bir program yaz.

def encrypt_message(message):
    encrypted_message = ""
    number_buffer = ""  # Sayıları geçici olarak tutacağımız değişken

    for char in message:
        if char.isalpha():
            if char.islower():
                new_char = chr((ord(char) - ord('a') + 5) % 26 + ord('a'))
            else:
                new_char = chr((ord(char) - ord('A') + 5) % 26 + ord('A'))
            encrypted_message += new_char
        elif char.isdigit():
            number_buffer += char
        else:
            if number_buffer:
                encrypted_message += number_buffer[::-1]
                number_buffer = ""
            encrypted_message += char

    if number_buffer:
        encrypted_message += number_buffer[::-1]

    return encrypted_message

def decrypt_message(message):
    decrypted_message = ""
    number_buffer = ""

    for char in message:
        if char.isalpha():
            if char.islower():
                new_char = chr((ord(char) - ord('a') - 5) % 26 + ord('a'))
            else:
                new_char = chr((ord(char) - ord('A') - 5) % 26 + ord('A'))
            decrypted_message += new_char
        elif char.isdigit():
            number_buffer += char
        else:
            if number_buffer:
                decrypted_message += number_buffer[::-1]
                number_buffer = ""
            decrypted_message += char

    if number_buffer:
        decrypted_message += number_buffer[::-1]

    return decrypted_message

# Kullanıcıdan mesaj alıp şifreleme
user_message = input("Şifrelemek istediğiniz mesajı girin: ")
encrypted_user_message = encrypt_message(user_message)
print("Şifreli mesaj:", encrypted_user_message)

# Şifreyi çözme
decrypted_user_message = decrypt_message(encrypted_user_message)
print("Şifreli mesajın çözülmüş hali:", decrypted_user_message)