# -*- coding: utf-8 -*-
"""Chatbot-Odev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7zYNBYb2wHjicHqMPUBG_kJCtlgHK7J

Şifrelenmiş mesajı çözen fonksiyon
"""

def decrypt_message(encrypted_msg):
    decrypted_msg = []

    for char in encrypted_msg:
        if char.isalpha():  # Eğer harfse
            # Harfi alfabede 5 harf geri al böylelikle tersine algoritma kullanarak çözmüş oluruz
            new_char = chr(((ord(char.lower()) - ord('a') - 5) % 26) + ord('a'))
            # Büyük harfse, büyük harf olarak yaz
            if char.isupper():
                new_char = new_char.upper()
            decrypted_msg.append(new_char)
        elif char.isdigit():  # Eğer rakamsa
            decrypted_msg.append(char[::-1])  # Sayıları ters çevir
        else:
            decrypted_msg.append(char)  # Boşluk ve noktalama işaretlerini değiştirme

    return ''.join(decrypted_msg)  #en son tüm yapılan değişiklikleri join ile birleştir

encrypted_msg = "ymj vznhp gwtbs ktc ozrux tajw ymj qfed itl"
decrypted_msg = decrypt_message(encrypted_msg)
print("Çözülmüş Mesaj:", decrypted_msg)

"""Bir mesajı şifreleyen fonksiyon"""

def encrypt_message(msg):
    encrypted_msg = []

    for char in msg:
        if char.isalpha():  # Eğer harfse
            # Harfi alfabede 5 harf ileri al
            new_char = chr(((ord(char.lower()) - ord('a') + 5) % 26) + ord('a'))
            # Büyük harfse, büyük harf olarak yaz
            if char.isupper():
                new_char = new_char.upper()
            encrypted_msg.append(new_char)
        elif char.isdigit():  # Eğer rakamsa
            encrypted_msg.append(char[::-1])  # Sayıları ters çevir
        else:
            encrypted_msg.append(char)  # Boşluk ve noktalama işaretlerini değiştirme

    return ''.join(encrypted_msg)

user_msg = input("Şifrelemek için bir mesaj girin: ")
encrypted_user_msg = encrypt_message(user_msg)
print("Şifrelenen Mesaj:", encrypted_user_msg)

decrypted_user_msg = decrypt_message(encrypted_user_msg)
print("Şifresi Çözülmüş olan Girilen Mesaj:", decrypted_user_msg)